homepage:
    path:     /
    defaults: { _controller: WreckThemBundle:Page:index }

register:
    path:     /registro
    defaults: { _controller: WreckThemBundle:User:register }

login:
    path:     /entrar
    defaults: { _controller: WreckThemBundle:User:login }

perfil:
    path:     /perfil
    defaults: { _controller: WreckThemBundle:User:perfil }

logout:
  path: /logout
