# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        AppBundle\Entity\User: bcrypt

    access_control:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/entrar, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/.+, roles: ROLE_USER } # FIXME para acceder al _profiler



    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: email
                # if you're using multiple entity managers
                # manager_name: customer


    firewalls:
        main:
            provider: our_db_provider
            anonymous: ~
            form_login:
                login_path: /
                check_path: /
            logout:
                path:   /logout
                target: /
