# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        WreckThemBundle\Entity\User: bcrypt

    access_control:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/entrar, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/*, roles: ROLE_USER }



    providers:
        our_db_provider:
            entity:
                class: WreckThemBundle:User
                property: email
                # if you're using multiple entity managers
                # manager_name: customer


    firewalls:
        main:
            provider: our_db_provider
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /
